### ISSUE TITLE
Possible WA 

### ISSUE THREAD

**Issue by ArthurConmy** [basimkhajwal/ProgrammingChallenges#2]
https://github.com/basimkhajwal/ProgrammingChallenges/blob/5aa184752cd7afe4122c812094fb66373ff63768/BIO%20Solutions/2015/round2/river.cpp#L4

Hello Basim,

Testing this solution locally led to a discrepancy between mine and your solution on the test case

5
4
1 10
10 10
10 10
10 10
10 1

My code gives 80 for this test, which I think is the correct answer, whereas yours gives 71.

My code can be found here: https://github.com/ArthurConmy/British-Informatics-Solutions/blob/master/2015%20river.cpp

**Comment by basimkhajwal** [comment]
Hi,
You're correct, seems I didn't test it properly. It should be fixed now with the latest commit 47291e97c6711079e6f6ae2d77022ca181bfab39.
